---
  - name: add Debian strech stretch sources
    template: src=stretch.list.j2 dest=/etc/apt/sources.list.d/stretch.list mode=0644
    register: stretch_sources_added

  - name: add apt pinning preferences files
    template: src=preferences.j2 dest=/etc/apt/preferences mode=0644

  # - name: add nginx official repo apt list file
  #   template: src=nginx.list.j2 dest=/etc/apt/sources.list.d/nginx.list mode=0644
  #   register: official_repo_added
  #
  # - name: add nginx official repo key
  #   apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  #   when: official_repo_added.changed

  - name: Update apt cache
    apt: update_cache=yes
    when: stretch_sources_added.changed

  # - name: Ensure nginx is installed
  #   apt:
  #     name: "{{ nginx_package_name }}"
  #     state: present
  #     force: yes
  #     default_release: stretch

  - name: Temp install
    command: apt-get install -yq nginx -t stretch -o APT::Force-LoopBreak=1
    changed_when: false

  - name: Ensure nginx is started and enabled to start at boot.
    service: name=nginx state=started enabled=yes


  - name: Remove default configuration
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "/etc/nginx/sites-enabled/default"
      - "/etc/nginx/sites-available/default"
      - "/etc/nginx/conf.d/default.conf"

  - name: Write nginx.conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: Rsync files
    synchronize: src=files/ dest=/etc/nginx/conf.d
    notify:
      - restart nginx

  - name: Create dhparam
    command: openssl dhparam -out {{nginx_dhparam_path}} {{nginx_dhparam_encryption_size}}
    args:
      creates: "{{nginx_dhparam_path}}"
    when: nginx_dhparam_path is defined and nginx_dhparam_path
    
  - name: Validate Nginx configuration
    shell: "nginx -t"
    register: result
    changed_when: "result.rc != 0"
    always_run: yes
